data=$(cat tablesample/anchors_with_role_button.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Anchors with role='button'" $data
data=$(cat tablesample/audio_track_usage.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Audio elements track usage" $data
data=$(cat tablesample/button_name_sources.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Where button elements get their A11Y names from" $data
data=$(cat tablesample/captcha_usage.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Captcha usage" $data
data=$(cat tablesample/color_contrast.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="% mobile sites with sufficient text color contrast with its background" $data
data=$(cat tablesample/common_alt_text_length.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Most common lengths of alt text" $data
data=$(cat tablesample/common_html_lang_attrib.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="% of mobile sites with a valid html lang attribute" $data
data=$(cat tablesample/form_input_name_sources.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Where input elements get their A11Y names from" $data
data=$(cat tablesample/form_required_controls.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Various stats for required form controls" $data
data=$(cat tablesample/page_title.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Page title stats" $data
data=$(cat tablesample/placeholder_but_no_label.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Form controls with placeholder but no label" $data
data=$(cat tablesample/sites_using_role.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Sites using the role attribute" $data
data=$(cat tablesample/sr_only_classes.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Sites using sr-only or visually-hidden classes" $data
data=$(cat tablesample/tabindex_usage_and_values.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Tabindex usage data" $data
data=$(cat tablesample/table_stats.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Table stats" $data
data=$(cat tablesample/viewport_zoom_scale.tablesample.csv.json); google-sheet data:append --spreadsheetId=1j32TLdG7uLUfYYwnVjWhN-WKf18EnFUbR8MV5QI9Umw --worksheetTitle="Viewport zoom scale" $data
